// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soinsoft.FleetUp.Infra.Persistence.Data;

#nullable disable

namespace Soinsoft.FleetUp.Infra.Persistence.Migrations
{
    [DbContext(typeof(FleetUpDbContext))]
    [Migration("20220323191443_Seed Data Added")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Blue",
                            CreatedOn = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentValue = 555m,
                            Description = "For Production",
                            Make = "Honda",
                            Model = "Masda",
                            VIN = "A55-522",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            CreatedOn = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentValue = 555m,
                            Description = "For Sales Department",
                            Make = "Honda",
                            Model = "Masda",
                            VIN = "F5588",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Blue",
                            CreatedOn = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentValue = 555m,
                            Description = "For Employees",
                            Make = "Honda",
                            Model = "Masda",
                            VIN = "QE-5426",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Blue",
                            CreatedOn = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentValue = 555m,
                            Description = "For CEO",
                            Make = "Honda",
                            Model = "Masda",
                            VIN = "W690001",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Blue",
                            CreatedOn = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentValue = 555m,
                            Description = "For Transporting",
                            Make = "Honda",
                            Model = "Masda",
                            VIN = "PA-59977",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Blue",
                            CreatedOn = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentValue = 555m,
                            Description = "For Production 2",
                            Make = "Honda",
                            Model = "Masda",
                            VIN = "DO1005",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Blue",
                            CreatedOn = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentValue = 555m,
                            Description = "For Events",
                            Make = "Honda",
                            Model = "Masda",
                            VIN = "AF97-23",
                            Year = "2020"
                        });
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.AssetInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetInfo");
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("MilesToExecuteTask")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolsNeeded")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maintenances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedCost = 2500m,
                            MilesToExecuteTask = 5000,
                            TaskDetails = "Replace",
                            Title = "Change Tires",
                            ToolsNeeded = "ToolBox A357"
                        },
                        new
                        {
                            Id = 2,
                            EstimatedCost = 500m,
                            MilesToExecuteTask = 5000,
                            TaskDetails = "Replace",
                            Title = "Change Oil",
                            ToolsNeeded = "ToolBox Q977"
                        },
                        new
                        {
                            Id = 3,
                            EstimatedCost = 350m,
                            MilesToExecuteTask = 5000,
                            TaskDetails = "Review",
                            Title = "Check Engine",
                            ToolsNeeded = "ToolBox D-1002"
                        });
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.MaintenanceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceInfo");
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaintenanceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            MaintenanceId = 3
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 1,
                            MaintenanceId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 1,
                            MaintenanceId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssetId = 2,
                            MaintenanceId = 3
                        },
                        new
                        {
                            Id = 5,
                            AssetId = 3,
                            MaintenanceId = 2
                        },
                        new
                        {
                            Id = 6,
                            AssetId = 4,
                            MaintenanceId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssetId = 5,
                            MaintenanceId = 2
                        },
                        new
                        {
                            Id = 8,
                            AssetId = 5,
                            MaintenanceId = 3
                        },
                        new
                        {
                            Id = 9,
                            AssetId = 6,
                            MaintenanceId = 2
                        },
                        new
                        {
                            Id = 10,
                            AssetId = 7,
                            MaintenanceId = 3
                        },
                        new
                        {
                            Id = 11,
                            AssetId = 7,
                            MaintenanceId = 2
                        },
                        new
                        {
                            Id = 12,
                            AssetId = 7,
                            MaintenanceId = 1
                        });
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssetInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractorID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfExecution")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaintenanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaintenanceInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskExecuted")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetInfoId");

                    b.HasIndex("MaintenanceInfoId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Soinsoft.FleetUp.Domain.Entities.Asset", null)
                        .WithMany("Schedules")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("Soinsoft.FleetUp.Domain.Entities.AssetInfo", "AssetInfo")
                        .WithMany()
                        .HasForeignKey("AssetInfoId");

                    b.HasOne("Soinsoft.FleetUp.Domain.Entities.MaintenanceInfo", "MaintenanceInfo")
                        .WithMany()
                        .HasForeignKey("MaintenanceInfoId");

                    b.Navigation("AssetInfo");

                    b.Navigation("MaintenanceInfo");
                });

            modelBuilder.Entity("Soinsoft.FleetUp.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
